name: poptart_workspace
description: Workspace tooling and package orchestration for the Poptart Dart packages.
version: 0.1.0
publish_to: none
homepage: https://poptart.xyz
documentation: https://poptart.xyz
repository: https://github.com/sprksocial/poptart
issue_tracker: https://github.com/sprksocial/poptart/issues

environment:
  sdk: ">=3.8.0 <4.0.0"

workspace:
  - packages/poptart
  - packages/poptart_core
  - packages/poptart_oauth
  - packages/poptart_test
  - packages/poptart_did_plc
  - packages/poptart_lex_gen
  - packages/poptart_lex
  - packages/poptart_lexicon
  - packages/poptart_multiformats
  - packages/poptart_primitives
  - packages/poptart_xrpc

dependencies:
  github: ^9.12.0
  http: ^1.4.0
  poptart_lex_gen: ^0.3.0
  poptart_lex: ^0.2.0
  poptart_lexicon: ^0.1.0
  pubspec: ^2.3.0
  test: ^1.26.2

dev_dependencies:
  lints: ^6.0.0
  melos: ^7.1.0
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces

melos:
  scripts:
    setup:
      run: |
        melos get
        melos build
      description: Set up the Poptart project when cloned. Run `dart pub get` and `dart run build_runner build` in all Dart packages.

    get:
      run: melos exec -c 20 -- \
        dart pub get
      description: Run `dart pub get` command in all packages.

    analyze:
      run: |
        melos exec -c 20 -- \
          flutter analyze .
      description: |
        Run `dart analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.

    fmt:
      run: |
        melos exec --depends-on="import_sorter" -c 20 -- dart run import_sorter
        melos exec -c 20 -- dart format .
      description: Run `dart format` and `dart run import_sorter:main` in all packages.

    build:
      run: |
        melos exec --depends-on="build_runner" -c 20 -- \
          dart run build_runner build clean
        melos exec --depends-on="build_runner" -c 1 -- \
          dart run build_runner build --delete-conflicting-outputs
      description: Run `dart run build_runner build` in all packages.

    test:
      run: melos exec --ignore="poptart_test,poptart_oauth,poptart_lex_gen" -- dart test
      description: Run all Dart tests in this project.
      flutter: false
      dir-exists: test

    publish_all:
      run: |
        dart run melos publish
        dart run melos publish --no-dry-run --git-tag-version --yes
        git push origin --tags
      description: Publish all packages, create git tags and push them to origin.

    gen:
      run: |
        dart run ./scripts/gen_lexicon_docs.dart
        dart run ./scripts/gen_lexicon_ids.dart
        dart run poptart_lex_gen generate
        cd packages/poptart_lex
        dart run build_runner build --delete-conflicting-outputs
        dart fix --apply
        cd ../../
        melos fmt
      description: Generate Poptart code from manifest-driven lexicons.
