name: poptart_lex_gen
description: Code generator for building Dart models and runtime descriptors from AT Protocol lexicons.
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  poptart_lexicon: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces
