name: poptart_core
resolution: workspace
description: Core library for clients and tools. This package is mainly used by https://atprotodart.com packages.
version: 0.1.1
homepage: https://poptart.xyz
documentation: https://poptart.xyz
repository: https://github.com/sprksocial/poptart
issue_tracker: https://github.com/sprksocial/poptart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api
  - core

dependencies:
  poptart_xrpc: ^0.1.0
  poptart_primitives: ^0.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cbor: ^6.3.7
  poptart_multiformats: ^0.1.0
  poptart_oauth: ^0.1.1
  nanoid: ^1.0.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.2.0
  http: ^1.6.0
  import_sorter:
    git:
      url: https://github.com/myConsciousness/import_sorter.git
      ref: fix/monorepo-pub-workspaces

  poptart_test:
    path: ../poptart_test
